### ISSUE TITLE
Handle multiple tabs using the same URL

### ISSUE THREAD

**Issue by AhsanAyaz** [appliedtechnology/chrome-extension-github-classroom-helper#4]
## Problem
At the moment, if you have multiple tabs using the same URL, the extension treats them as multiple pages.
This could result in some discrepancies which could be avoided.
  
## Solution
If there are multiple tabs with the same URL, use the first one of them only.

**Comment by LaylaSilbernberg** [comment]
I'll work on this one!

**Comment by AhsanAyaz** [comment]
Fixed by #9
